version: 2

sources:
  - name: dbx_datasets_retail_org
    description: "A sample dataset provided by databricks"
    database: retail_org
    schema: retail_org
    tables:
      - name: sales_orders
        description: "Details about the sales orders"
        
